# To choose a Python version, first create the env with:
# conda create -n sparkdl python=3.6
# and then update it
# conda env update -n sparkdl -f environment.yml
name: sparkdl
channels:
- https://repo.anaconda.com/pkgs/main/linux-64/
dependencies:
# runtime
- six=1.11.0
- nomkl # do not install MKL because it is large
- pandas=0.23.4
- h5py=2.8.0
- pillow=4.1.1
- cloudpickle=0.5.2
- tensorflow=1.12.0
- keras=2.2.4
- paramiko=2.4.1
- wrapt=1.10.11
# test
- coverage=4.5.1
- nose=1.3.7
- parameterized=0.6.1
- pylint=1.8.4
- argcomplete=1.9.4
- PyYAML=3.13
- pip:
  # runtime
  - horovod==0.15.2
  # test
  - prospector==0.12.11
  - argh==0.26.2
  - yapf==0.21.0
  # docs
  - sphinx
